services:
  ros-dev:
    # image: rishikesavanramesh/ros2-dev # change this to your docker image
    # image: localhost/ros2_ros-dev # change this to your docker image
    build: .
    volumes:
      - ../../.:/workspace/.:rw
      - /tmp/.X11-unix:/tmp/.X11-unix # Expose X11 socket
      # - /dev:/dev:rw
    environment:
      - DISPLAY=:45 # ( see https://gist.github.com/RishikesavanRamesh/d8c085c958bc11e8562cd3db297e4eb8 )

    command: sleep infinity
    # network_mode: host
    
    # ipc: host
    # pid: host


    security_opt: # strictly for developement 
      - seccomp:unconfined
    cap_add: # strictly for developement 
      # - SYS_PTRACE
      - all

    device_cgroup_rules: # (ref https://www.kernel.org/doc/Documentation/admin-guide/devices.txt )
      - 'c 13:* rwm'  # Input core ( eg : joystick)
      - 'c 166:* rwm' # ACM USB modems 
      - 'c 167:* rwm'   # & its alternate devices
      - 'c 188:* rwm' # USB serial converters 
      - 'c 189:* rwm'   # 1& its alternate devices    