services:
  ros-dev:
    # image: rishikesavanramesh/ros2-dev # change this to your docker image
    build: .
    volumes:
      - ../../.:/workspace/.:rw
      - /tmp/.X11-unix:/tmp/.X11-unix # Expose X11 socket
    environment:
      - SSH_KEY=$SSH_KEY
      - DISPLAY=:45
    command: sleep infinity
    user: developer
