services:
  ros-dev:
    # image: rishikesavanramesh/ros2-dev # change this to your docker image
    build: .
    volumes:
      - ../../.:/workspace/.:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw # Expose X11 socket
      - ${XAUTHORITY:-$HOME/.Xauthority}:/home/developer/.Xauthority # Mount Xauthority file
    environment:
      - SSH_KEY=$SSH_KEY
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/home/developer/.Xauthority # Set Xauthority file path
    command: sleep infinity
    user: developer
