services:
  ros-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../.:/workspace
    command: sleep infinity
    environment:
      - DISPLAY=vnc:0.0
    depends_on:
      - vnc
    networks:
      - x11
  vnc:
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:
