# override.yml
services:
  ros-dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      - DISPLAY=vnc:0.0
    depends_on:
      vnc:
        condition: service_started
    networks:
      - x11
      
  vnc:
    # image: theasp/novnc:latest
    image: manojm003/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:
    driver: bridge